// Allow-listed IPC channel names shared across main, preload, and renderer.
// Keeping them in one place keeps the contract typed and prevents drift.
export const IpcChannels = {
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowClose: 'window:close',
  windowIsMaximized: 'window:is-maximized',
  windowMaximizeChanged: 'window:maximize-changed',
  appVersion: 'app:version',
  clientsList: 'clients:list',
  clientsGet: 'clients:get',
  clientsCreate: 'clients:create',
  clientsUpdate: 'clients:update',
  clientsDelete: 'clients:delete',
  databaseExportClientsCsv: 'database:export-clients-csv',
  databaseGetDataDir: 'database:get-data-dir',
  databaseOpenDataFolder: 'database:open-data-folder',
  authGetStatus: 'auth:get-status',
  authActivate: 'auth:activate',
  authSetPassword: 'auth:set-password',
  authLogin: 'auth:login',
  authLogOut: 'auth:log-out',
  authSelectAccount: 'auth:select-account',
  authBeginAddAccount: 'auth:begin-add-account',
  authReturnToLogin: 'auth:return-to-login',
  authGetSecuritySettings: 'auth:get-security-settings',
  authSetLoginPolicy: 'auth:set-login-policy',
  templatesList: 'templates:list',
  templatesGet: 'templates:get',
  templatesCreate: 'templates:create',
  templatesUpdate: 'templates:update',
  templatesDelete: 'templates:delete',
  templatesDuplicate: 'templates:duplicate',
  templatesExportJson: 'templates:export-json',
  templatesImportJson: 'templates:import-json',
  templatesExportSchemaKit: 'templates:export-schema-kit',
  inspectionsList: 'inspections:list',
  inspectionsGet: 'inspections:get',
  inspectionsCreate: 'inspections:create',
  inspectionsUpdate: 'inspections:update',
  inspectionsDelete: 'inspections:delete',
  inspectionsDashboard: 'inspections:dashboard',
  inspectionsClientStats: 'inspections:client-stats',
  inspectionsExportPdf: 'inspections:export-pdf',
  inspectionsImportPdf: 'inspections:import-pdf',
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
